export interface Avatar {
  id: string;
  emoji: string;
  label: string;
}

export const avatars: Avatar[] = [
  // Kids
  { id: 'boy1', emoji: '👦', label: 'Boy' },
  { id: 'boy2', emoji: '👦🏽', label: 'Boy' },
  { id: 'girl1', emoji: '👧', label: 'Girl' },
  { id: 'girl2', emoji: '👧🏽', label: 'Girl' },

  // Fun Characters
  { id: 'robot', emoji: '🤖', label: 'Robot' },
  { id: 'alien', emoji: '👽', label: 'Alien' },
  { id: 'prince', emoji: '🤴', label: 'Prince' },
  { id: 'princess', emoji: '👸', label: 'Princess' },
  { id: 'clown', emoji: '🤡', label: 'Clown' },
  { id: 'ghost', emoji: '👻', label: 'Ghost' },
  { id: 'superhero', emoji: '🦸', label: 'Hero' },
  { id: 'supervillain', emoji: '🦹', label: 'Villain' },

  // Animals
  { id: 'cat', emoji: '🐱', label: 'Cat' },
  { id: 'dog', emoji: '🐶', label: 'Dog' },
  { id: 'tiger', emoji: '🐯', label: 'Tiger' },
  { id: 'panda', emoji: '🐼', label: 'Panda' },
  { id: 'fox', emoji: '🦊', label: 'Fox' },
  { id: 'dino', emoji: '🦖', label: 'Dino' },
  { id: 'unicorn', emoji: '🦄', label: 'Unicorn' },
  { id: 'dragon', emoji: '🐉', label: 'Dragon' },
  { id: 'elephant', emoji: '🐘', label: 'Elephant' },
  { id: 'lion', emoji: '🦁', label: 'Lion' },
  { id: 'penguin', emoji: '🐧', label: 'Penguin' },
  { id: 'koala', emoji: '🐨', label: 'Koala' },
  { id: 'monkey', emoji: '🐵', label: 'Monkey' },
  { id: 'rabbit', emoji: '🐰', label: 'Rabbit' },
  { id: 'bear', emoji: '🐻', label: 'Bear' },

  // Fantasy & Professions
  { id: 'wizard', emoji: '🧙', label: 'Wizard' },
  { id: 'fairy', emoji: '🧚', label: 'Fairy' },
  { id: 'vampire', emoji: '🧛', label: 'Vampire' },
  { id: 'mermaid', emoji: '🧜‍♀️', label: 'Mermaid' },
  { id: 'elf', emoji: '🧝', label: 'Elf' },
  { id: 'genie', emoji: '🧞', label: 'Genie' },
  { id: 'zombie', emoji: '🧟', label: 'Zombie' },
  { id: 'ninja', emoji: '🥷', label: 'Ninja' },

  // More Professions
  { id: 'astronaut', emoji: '🧑‍🚀', label: 'Astronaut' },
  { id: 'detective', emoji: '🕵️', label: 'Detective' },
  { id: 'chef', emoji: '👨‍🍳', label: 'Chef' },
  { id: 'artist', emoji: '👩‍🎨', label: 'Artist' },
  { id: 'scientist', emoji: '👩‍🔬', label: 'Scientist' },
  { id: 'superhero2', emoji: '🦸‍♂️', label: 'Superhero' },
  { id: 'superhero3', emoji: '🦸‍♀️', label: 'Heroine' },
  { id: 'doctor', emoji: '👩‍⚕️', label: 'Doctor' },
  { id: 'teacher', emoji: '👩‍🏫', label: 'Teacher' },
  { id: 'firefighter', emoji: '👨‍🚒', label: 'Firefighter' },
  { id: 'police', emoji: '👮‍♀️', label: 'Police' },
  { id: 'pilot', emoji: '👨‍✈️', label: 'Pilot' },
  { id: 'farmer', emoji: '👩‍🌾', label: 'Farmer' },

  // Sports & Activities
  { id: 'soccer', emoji: '⚽', label: 'Soccer' },
  { id: 'basketball', emoji: '🏀', label: 'Basketball' },
  { id: 'tennis', emoji: '🎾', label: 'Tennis' },
  { id: 'baseball', emoji: '⚾', label: 'Baseball' },
  { id: 'golf', emoji: '⛳', label: 'Golf' },
  { id: 'swimmer', emoji: '🏊‍♀️', label: 'Swimmer' },
  { id: 'cyclist', emoji: '🚴‍♂️', label: 'Cyclist' },
  { id: 'skier', emoji: '🎿', label: 'Skier' },
  { id: 'surfer', emoji: '🏄‍♀️', label: 'Surfer' },
  { id: 'dancer', emoji: '💃', label: 'Dancer' },
  { id: 'musician', emoji: '🎵', label: 'Musician' },

  // Nature & Weather
  { id: 'sun', emoji: '☀️', label: 'Sun' },
  { id: 'moon', emoji: '🌙', label: 'Moon' },
  { id: 'star', emoji: '⭐', label: 'Star' },
  { id: 'cloud', emoji: '☁️', label: 'Cloud' },
  { id: 'rainbow', emoji: '🌈', label: 'Rainbow' },
  { id: 'flower', emoji: '🌸', label: 'Flower' },
  { id: 'tree', emoji: '🌳', label: 'Tree' },
  { id: 'cactus', emoji: '🌵', label: 'Cactus' },
  { id: 'ocean', emoji: '🌊', label: 'Ocean' },
  { id: 'mountain', emoji: '🏔️', label: 'Mountain' },
  { id: 'volcano', emoji: '🌋', label: 'Volcano' },

  // More Fun Characters
  { id: 'pirate', emoji: '🏴‍☠️', label: 'Pirate' },
  { id: 'cowboy', emoji: '🤠', label: 'Cowboy' },
  { id: 'ballerina', emoji: '🩰', label: 'Ballerina' },
  { id: 'magician', emoji: '🎩', label: 'Magician' },
  { id: 'rockstar', emoji: '🎸', label: 'Rockstar' },
  { id: 'chef2', emoji: '🍳', label: 'Cook' },
  { id: 'baker', emoji: '🍞', label: 'Baker' },
  { id: 'gardener', emoji: '🌻', label: 'Gardener' },
  { id: 'explorer', emoji: '🗺️', label: 'Explorer' },
  { id: 'inventor', emoji: '🔧', label: 'Inventor' },
  { id: 'photographer', emoji: '📸', label: 'Photographer' },
  { id: 'writer', emoji: '✍️', label: 'Writer' },

  // Space & Tech
  { id: 'rocket', emoji: '🚀', label: 'Rocket' },
  { id: 'satellite', emoji: '🛰️', label: 'Satellite' },
  { id: 'computer', emoji: '💻', label: 'Computer' },
  { id: 'phone', emoji: '📱', label: 'Phone' },
  { id: 'game', emoji: '🎮', label: 'Gamer' },
  { id: 'camera', emoji: '📷', label: 'Camera' },

  // More Fantasy
  { id: 'knight', emoji: '⚔️', label: 'Knight' },
  { id: 'pixie', emoji: '✨', label: 'Pixie' },
  { id: 'troll', emoji: '👹', label: 'Troll' },
  { id: 'angel', emoji: '👼', label: 'Angel' },
  { id: 'devil', emoji: '😈', label: 'Devil' },
  { id: 'monster', emoji: '👾', label: 'Monster' },
  { id: 'phoenix', emoji: '🔥', label: 'Phoenix' },
  { id: 'pegasus', emoji: '🦄', label: 'Pegasus' },

  // Food & Drinks
  { id: 'pizza', emoji: '🍕', label: 'Pizza' },
  { id: 'burger', emoji: '🍔', label: 'Burger' },
  { id: 'hotdog', emoji: '🌭', label: 'Hot Dog' },
  { id: 'taco', emoji: '🌮', label: 'Taco' },
  { id: 'burrito', emoji: '🌯', label: 'Burrito' },
  { id: 'spaghetti', emoji: '🍝', label: 'Spaghetti' },
  { id: 'icecream', emoji: '🍦', label: 'Ice Cream' },
  { id: 'cake', emoji: '🎂', label: 'Cake' },
  { id: 'cookie', emoji: '🍪', label: 'Cookie' },
  { id: 'donut', emoji: '🍩', label: 'Donut' },
  { id: 'candy', emoji: '🍬', label: 'Candy' },
  { id: 'lollipop', emoji: '🍭', label: 'Lollipop' },
  { id: 'popcorn', emoji: '🍿', label: 'Popcorn' },
  { id: 'pretzel', emoji: '🥨', label: 'Pretzel' },
  { id: 'croissant', emoji: '🥐', label: 'Croissant' },
  { id: 'bread', emoji: '🍞', label: 'Bread' },
  { id: 'cheese', emoji: '🧀', label: 'Cheese' },
  { id: 'egg', emoji: '🥚', label: 'Egg' },
  { id: 'bacon', emoji: '🥓', label: 'Bacon' },
  { id: 'chicken', emoji: '🍗', label: 'Chicken' },
  { id: 'steak', emoji: '🥩', label: 'Steak' },
  { id: 'fish', emoji: '🐟', label: 'Fish' },
  { id: 'shrimp', emoji: '🦐', label: 'Shrimp' },
  { id: 'apple', emoji: '🍎', label: 'Apple' },
  { id: 'banana', emoji: '🍌', label: 'Banana' },
  { id: 'orange', emoji: '🍊', label: 'Orange' },
  { id: 'grapes', emoji: '🍇', label: 'Grapes' },
  { id: 'strawberry', emoji: '🍓', label: 'Strawberry' },
  { id: 'watermelon', emoji: '🍉', label: 'Watermelon' },
  { id: 'pineapple', emoji: '🍍', label: 'Pineapple' },
  { id: 'peach', emoji: '🍑', label: 'Peach' },
  { id: 'cherry', emoji: '🍒', label: 'Cherry' },
  { id: 'lemon', emoji: '🍋', label: 'Lemon' },
  { id: 'coconut', emoji: '🥥', label: 'Coconut' },
  { id: 'avocado', emoji: '🥑', label: 'Avocado' },
  { id: 'broccoli', emoji: '🥦', label: 'Broccoli' },
  { id: 'carrot', emoji: '🥕', label: 'Carrot' },
  { id: 'corn', emoji: '🌽', label: 'Corn' },
  { id: 'pepper', emoji: '🌶️', label: 'Pepper' },
  { id: 'mushroom', emoji: '🍄', label: 'Mushroom' },
  { id: 'peanut', emoji: '🥜', label: 'Peanut' },
  { id: 'coffee', emoji: '☕', label: 'Coffee' },
  { id: 'tea', emoji: '🍵', label: 'Tea' },
  { id: 'beer', emoji: '🍺', label: 'Beer' },
  { id: 'wine', emoji: '🍷', label: 'Wine' },
  { id: 'cocktail', emoji: '🍸', label: 'Cocktail' },
  { id: 'champagne', emoji: '🥂', label: 'Champagne' },

  // Vehicles & Transportation
  { id: 'car', emoji: '🚗', label: 'Car' },
  { id: 'taxi', emoji: '🚕', label: 'Taxi' },
  { id: 'bus', emoji: '🚌', label: 'Bus' },
  { id: 'truck', emoji: '🚛', label: 'Truck' },
  { id: 'police_car', emoji: '🚓', label: 'Police Car' },
  { id: 'ambulance', emoji: '🚑', label: 'Ambulance' },
  { id: 'fire_truck', emoji: '🚒', label: 'Fire Truck' },
  { id: 'motorcycle', emoji: '🏍️', label: 'Motorcycle' },
  { id: 'bicycle', emoji: '🚲', label: 'Bicycle' },
  { id: 'scooter', emoji: '🛴', label: 'Scooter' },
  { id: 'airplane', emoji: '✈️', label: 'Airplane' },
  { id: 'helicopter', emoji: '🚁', label: 'Helicopter' },
  { id: 'train', emoji: '🚂', label: 'Train' },
  { id: 'subway', emoji: '🚇', label: 'Subway' },
  { id: 'ship', emoji: '🚢', label: 'Ship' },
  { id: 'boat', emoji: '⛵', label: 'Boat' },
  { id: 'speedboat', emoji: '🚤', label: 'Speedboat' },
  { id: 'ferry', emoji: '⛴️', label: 'Ferry' },
  { id: 'sailboat', emoji: '⛵', label: 'Sailboat' },
  { id: 'canoe', emoji: '🛶', label: 'Canoe' },
  { id: 'rocket_ship', emoji: '🚀', label: 'Rocket Ship' },
  { id: 'flying_saucer', emoji: '🛸', label: 'UFO' },
  { id: 'tractor', emoji: '🚜', label: 'Tractor' },
  { id: 'race_car', emoji: '🏎️', label: 'Race Car' },
  { id: 'taxi2', emoji: '🚕', label: 'Taxi' },

  // Musical Instruments
  { id: 'guitar', emoji: '🎸', label: 'Guitar' },
  { id: 'violin', emoji: '🎻', label: 'Violin' },
  { id: 'piano', emoji: '🎹', label: 'Piano' },
  { id: 'trumpet', emoji: '🎺', label: 'Trumpet' },
  { id: 'saxophone', emoji: '🎷', label: 'Saxophone' },
  { id: 'drum', emoji: '🥁', label: 'Drum' },
  { id: 'microphone', emoji: '🎤', label: 'Microphone' },
  { id: 'headphones', emoji: '🎧', label: 'Headphones' },
  { id: 'music_note', emoji: '🎵', label: 'Music Note' },
  { id: 'music_notes', emoji: '🎶', label: 'Music Notes' },
  { id: 'speaker', emoji: '🔊', label: 'Speaker' },
  { id: 'radio', emoji: '📻', label: 'Radio' },
  { id: 'accordion', emoji: '🪗', label: 'Accordion' },
  { id: 'banjo', emoji: '🪕', label: 'Banjo' },
  { id: 'flute', emoji: '🪈', label: 'Flute' },

  // Space & Science
  { id: 'telescope', emoji: '🔭', label: 'Telescope' },
  { id: 'microscope', emoji: '🔬', label: 'Microscope' },
  { id: 'atom', emoji: '⚛️', label: 'Atom' },
  { id: 'dna', emoji: '🧬', label: 'DNA' },
  { id: 'bacteria', emoji: '🦠', label: 'Bacteria' },
  { id: 'petri_dish', emoji: '🧫', label: 'Petri Dish' },
  { id: 'test_tube', emoji: '🧪', label: 'Test Tube' },
  { id: 'thermometer', emoji: '🌡️', label: 'Thermometer' },
  { id: 'gear', emoji: '⚙️', label: 'Gear' },
  { id: 'wrench', emoji: '🔧', label: 'Wrench' },
  { id: 'hammer', emoji: '🔨', label: 'Hammer' },
  { id: 'screwdriver', emoji: '🪛', label: 'Screwdriver' },
  { id: 'toolbox', emoji: '🧰', label: 'Toolbox' },
  { id: 'nut_and_bolt', emoji: '🔩', label: 'Nut & Bolt' },
  { id: 'clamp', emoji: '🗜️', label: 'Clamp' },
  { id: 'balance_scale', emoji: '⚖️', label: 'Scale' },
  { id: 'alembic', emoji: '⚗️', label: 'Chemistry' },
  { id: 'compass', emoji: '🧭', label: 'Compass' },
  { id: 'hourglass', emoji: '⏳', label: 'Hourglass' },
  { id: 'stopwatch', emoji: '⏱️', label: 'Stopwatch' },
  { id: 'timer_clock', emoji: '⏲️', label: 'Timer' },
  { id: 'alarm_clock', emoji: '⏰', label: 'Alarm Clock' },
  { id: 'mantelpiece_clock', emoji: '🕰️', label: 'Clock' },

  // Holidays & Seasons
  { id: 'christmas_tree', emoji: '🎄', label: 'Christmas Tree' },
  { id: 'snowman', emoji: '☃️', label: 'Snowman' },
  { id: 'snowflake', emoji: '❄️', label: 'Snowflake' },
  { id: 'jack_o_lantern', emoji: '🎃', label: 'Pumpkin' },
  { id: 'candy_cane', emoji: '🍬', label: 'Candy Cane' },
  { id: 'gift', emoji: '🎁', label: 'Gift' },
  { id: 'balloon', emoji: '🎈', label: 'Balloon' },
  { id: 'party_popper', emoji: '🎉', label: 'Party' },
  { id: 'confetti', emoji: '🎊', label: 'Confetti' },
  { id: 'fireworks', emoji: '🎆', label: 'Fireworks' },
  { id: 'sparkler', emoji: '🎇', label: 'Sparkler' },
  { id: 'trophy', emoji: '🏆', label: 'Trophy' },
  { id: 'medal', emoji: '🏅', label: 'Medal' },
  { id: 'rosette', emoji: '🏵️', label: 'Rosette' },
  { id: 'reminder_ribbon', emoji: '🎗️', label: 'Ribbon' },
  { id: 'ticket', emoji: '🎫', label: 'Ticket' },
  { id: 'crown', emoji: '👑', label: 'Crown' },
  { id: 'gem_stone', emoji: '💎', label: 'Gem' },
  { id: 'ring', emoji: '💍', label: 'Ring' },
  { id: 'bouquet', emoji: '💐', label: 'Bouquet' },

  // Colors & Shapes
  { id: 'red_circle', emoji: '🔴', label: 'Red Circle' },
  { id: 'orange_circle', emoji: '🟠', label: 'Orange Circle' },
  { id: 'yellow_circle', emoji: '🟡', label: 'Yellow Circle' },
  { id: 'green_circle', emoji: '🟢', label: 'Green Circle' },
  { id: 'blue_circle', emoji: '🔵', label: 'Blue Circle' },
  { id: 'purple_circle', emoji: '🟣', label: 'Purple Circle' },
  { id: 'brown_circle', emoji: '🤎', label: 'Brown Circle' },
  { id: 'black_circle', emoji: '⚫', label: 'Black Circle' },
  { id: 'white_circle', emoji: '⚪', label: 'White Circle' },
  { id: 'red_square', emoji: '🟥', label: 'Red Square' },
  { id: 'orange_square', emoji: '🟧', label: 'Orange Square' },
  { id: 'yellow_square', emoji: '🟨', label: 'Yellow Square' },
  { id: 'green_square', emoji: '🟩', label: 'Green Square' },
  { id: 'blue_square', emoji: '🟦', label: 'Blue Square' },
  { id: 'purple_square', emoji: '🟪', label: 'Purple Square' },
  { id: 'brown_square', emoji: '🟫', label: 'Brown Square' },
  { id: 'black_square', emoji: '⬛', label: 'Black Square' },
  { id: 'white_square', emoji: '⬜', label: 'White Square' },
  { id: 'diamond', emoji: '💎', label: 'Diamond' },
  { id: 'star2', emoji: '⭐', label: 'Star' },
  { id: 'sparkles', emoji: '✨', label: 'Sparkles' },

  // Emotions & Expressions
  { id: 'grinning_face', emoji: '😀', label: 'Grinning' },
  { id: 'smiley', emoji: '😃', label: 'Smiley' },
  { id: 'smile', emoji: '😄', label: 'Smile' },
  { id: 'grin', emoji: '😁', label: 'Grin' },
  { id: 'laughing', emoji: '😆', label: 'Laughing' },
  { id: 'sweat_smile', emoji: '😅', label: 'Sweat Smile' },
  { id: 'rofl', emoji: '🤣', label: 'ROFL' },
  { id: 'joy', emoji: '😂', label: 'Joy' },
  { id: 'wink', emoji: '😉', label: 'Wink' },
  { id: 'blush', emoji: '😊', label: 'Blush' },
  { id: 'innocent', emoji: '😇', label: 'Innocent' },
  { id: 'heart_eyes', emoji: '😍', label: 'Heart Eyes' },
  { id: 'kissing_heart', emoji: '😘', label: 'Kissing Heart' },
  { id: 'relaxed', emoji: '☺️', label: 'Relaxed' },
  { id: 'sunglasses', emoji: '😎', label: 'Cool' },
  { id: 'stuck_out_tongue', emoji: '😛', label: 'Tongue Out' },
  { id: 'money_mouth', emoji: '🤑', label: 'Money' },
  { id: 'nerd_face', emoji: '🤓', label: 'Nerd' },
  { id: 'sunglasses2', emoji: '🕶️', label: 'Sunglasses' },
  { id: 'hugs', emoji: '🤗', label: 'Hugs' },
  { id: 'thinking', emoji: '🤔', label: 'Thinking' },

  // Body Parts
  { id: 'eye', emoji: '👁️', label: 'Eye' },
  { id: 'ear', emoji: '👂', label: 'Ear' },
  { id: 'nose', emoji: '👃', label: 'Nose' },
  { id: 'mouth', emoji: '👄', label: 'Mouth' },
  { id: 'tongue', emoji: '👅', label: 'Tongue' },
  { id: 'hand', emoji: '✋', label: 'Hand' },
  { id: 'foot', emoji: '🦶', label: 'Foot' },
  { id: 'brain', emoji: '🧠', label: 'Brain' },
  { id: 'heart', emoji: '❤️', label: 'Heart' },
  { id: 'lungs', emoji: '🫁', label: 'Lungs' },
  { id: 'tooth', emoji: '🦷', label: 'Tooth' },
  { id: 'bone', emoji: '🦴', label: 'Bone' },
  { id: 'eyes', emoji: '👀', label: 'Eyes' },
  { id: 'raised_hands', emoji: '🙌', label: 'Raised Hands' },
  { id: 'clap', emoji: '👏', label: 'Clap' },
  { id: 'thumbs_up', emoji: '👍', label: 'Thumbs Up' },
  { id: 'thumbs_down', emoji: '👎', label: 'Thumbs Down' },
  { id: 'fist', emoji: '✊', label: 'Fist' },
  { id: 'victory_hand', emoji: '✌️', label: 'Victory' },
  { id: 'crossed_fingers', emoji: '🤞', label: 'Crossed Fingers' },

  // Buildings & Structures
  { id: 'house', emoji: '🏠', label: 'House' },
  { id: 'house_with_garden', emoji: '🏡', label: 'House & Garden' },
  { id: 'school', emoji: '🏫', label: 'School' },
  { id: 'office', emoji: '🏢', label: 'Office' },
  { id: 'hospital', emoji: '🏥', label: 'Hospital' },
  { id: 'bank', emoji: '🏦', label: 'Bank' },
  { id: 'hotel', emoji: '🏨', label: 'Hotel' },
  { id: 'church', emoji: '⛪', label: 'Church' },
  { id: 'mosque', emoji: '🕌', label: 'Mosque' },
  { id: 'synagogue', emoji: '🕍', label: 'Synagogue' },
  { id: 'shinto_shrine', emoji: '⛩️', label: 'Temple' },
  { id: 'castle', emoji: '🏰', label: 'Castle' },
  { id: 'tower', emoji: '🗼', label: 'Tower' },
  { id: 'statue_of_liberty', emoji: '🗽', label: 'Statue' },
  { id: 'bridge', emoji: '🌉', label: 'Bridge' },
  { id: 'carousel_horse', emoji: '🎠', label: 'Carousel' },
  { id: 'ferris_wheel', emoji: '🎡', label: 'Ferris Wheel' },
  { id: 'roller_coaster', emoji: '🎢', label: 'Roller Coaster' },
  { id: 'circus_tent', emoji: '🎪', label: 'Circus' },
  { id: 'stadium', emoji: '🏟️', label: 'Stadium' },

  // Tools & Equipment
  { id: 'hammer2', emoji: '🔨', label: 'Hammer' },
  { id: 'axe', emoji: '🪓', label: 'Axe' },
  { id: 'pick', emoji: '⛏️', label: 'Pick' },
  { id: 'hammer_and_pick', emoji: '⚒️', label: 'Hammer & Pick' },
  { id: 'hammer_and_wrench', emoji: '🛠️', label: 'Tools' },
  { id: 'dagger', emoji: '🗡️', label: 'Dagger' },
  { id: 'crossed_swords', emoji: '⚔️', label: 'Swords' },
  { id: 'gun', emoji: '🔫', label: 'Gun' },
  { id: 'bow_and_arrow', emoji: '🏹', label: 'Bow & Arrow' },
  { id: 'shield', emoji: '🛡️', label: 'Shield' },
  { id: 'wrench2', emoji: '🔧', label: 'Wrench' },
  { id: 'nut_and_bolt2', emoji: '🔩', label: 'Nut & Bolt' },
  { id: 'gear2', emoji: '⚙️', label: 'Gear' },
  { id: 'clamp2', emoji: '🗜️', label: 'Clamp' },
  { id: 'balance_scale2', emoji: '⚖️', label: 'Scale' },
  { id: 'cane', emoji: '🦯', label: 'Cane' },
  { id: 'link', emoji: '🔗', label: 'Link' },
  { id: 'chains', emoji: '⛓️', label: 'Chains' },
  { id: 'toolbox2', emoji: '🧰', label: 'Toolbox' },

  // Games & Toys
  { id: 'ball', emoji: '⚽', label: 'Ball' },
  { id: 'basketball2', emoji: '🏀', label: 'Basketball' },
  { id: 'football', emoji: '🏈', label: 'Football' },
  { id: 'tennis2', emoji: '🎾', label: 'Tennis' },
  { id: 'volleyball', emoji: '🏐', label: 'Volleyball' },
  { id: 'rugby', emoji: '🏉', label: 'Rugby' },
  { id: 'flying_disc', emoji: '🥏', label: 'Frisbee' },
  { id: 'boomerang', emoji: '🪃', label: 'Boomerang' },
  { id: 'yo_yo', emoji: '🪀', label: 'Yo-Yo' },
  { id: 'kite', emoji: '🪁', label: 'Kite' },
  { id: 'pool_8_ball', emoji: '🎱', label: '8 Ball' },
  { id: 'crystal_ball', emoji: '🔮', label: 'Crystal Ball' },
  { id: 'nazar_amulet', emoji: '🧿', label: 'Nazar' },
  { id: 'teddy_bear', emoji: '🧸', label: 'Teddy Bear' },
  { id: 'piñata', emoji: '🪅', label: 'Piñata' },
  { id: 'nesting_dolls', emoji: '🪆', label: 'Nesting Dolls' },
  { id: 'chess_pawn', emoji: '♟️', label: 'Chess' },
  { id: 'joker', emoji: '🃏', label: 'Joker' },
  { id: 'mahjong', emoji: '🀄', label: 'Mahjong' },
  { id: 'flower_playing_cards', emoji: '🎴', label: 'Cards' },

  // Clothing & Accessories
  { id: 'tshirt', emoji: '👕', label: 'T-Shirt' },
  { id: 'jeans', emoji: '👖', label: 'Jeans' },
  { id: 'dress', emoji: '👗', label: 'Dress' },
  { id: 'kimono', emoji: '👘', label: 'Kimono' },
  { id: 'bikini', emoji: '👙', label: 'Bikini' },
  { id: 'shirt', emoji: '👔', label: 'Shirt' },
  { id: 'coat', emoji: '🧥', label: 'Coat' },
  { id: 'scarf', emoji: '🧣', label: 'Scarf' },
  { id: 'gloves', emoji: '🧤', label: 'Gloves' },
  { id: 'socks', emoji: '🧦', label: 'Socks' },
  { id: 'shoes', emoji: '👟', label: 'Shoes' },
  { id: 'boot', emoji: '👢', label: 'Boot' },
  { id: 'high_heel', emoji: '👠', label: 'High Heel' },
  { id: 'sandal', emoji: '👡', label: 'Sandal' },
  { id: 'hat', emoji: '👒', label: 'Hat' },
  { id: 'cap', emoji: '🧢', label: 'Cap' },
  { id: 'beanie', emoji: '🎩', label: 'Beanie' },
  { id: 'glasses', emoji: '👓', label: 'Glasses' },
  { id: 'sunglasses3', emoji: '🕶️', label: 'Sunglasses' },
  { id: 'necktie', emoji: '👔', label: 'Necktie' },
  { id: 'watch', emoji: '⌚', label: 'Watch' },
  { id: 'purse', emoji: '👛', label: 'Purse' },
  { id: 'handbag', emoji: '👜', label: 'Handbag' },
  { id: 'briefcase', emoji: '💼', label: 'Briefcase' },
  { id: 'backpack', emoji: '🎒', label: 'Backpack' },

  // Furniture & Home
  { id: 'chair', emoji: '🪑', label: 'Chair' },
  { id: 'couch_and_lamp', emoji: '🛋️', label: 'Couch' },
  { id: 'bed', emoji: '🛏️', label: 'Bed' },
  { id: 'door', emoji: '🚪', label: 'Door' },
  { id: 'window', emoji: '🪟', label: 'Window' },
  { id: 'mirror', emoji: '🪞', label: 'Mirror' },
  { id: 'picture_frame', emoji: '🖼️', label: 'Picture Frame' },
  { id: 'toilet', emoji: '🚽', label: 'Toilet' },
  { id: 'shower', emoji: '🚿', label: 'Shower' },
  { id: 'bathtub', emoji: '🛁', label: 'Bathtub' },
  { id: 'sink', emoji: '🛀', label: 'Sink' },
  { id: 'lamp', emoji: '💡', label: 'Lamp' },
  { id: 'candle', emoji: '🕯️', label: 'Candle' },
  { id: 'fireplace', emoji: '🔥', label: 'Fireplace' },
  { id: 'heater', emoji: '🌡️', label: 'Heater' },
  { id: 'fan', emoji: '💨', label: 'Fan' },
  { id: 'umbrella', emoji: '☂️', label: 'Umbrella' },
  { id: 'umbrella_on_ground', emoji: '⛱️', label: 'Beach Umbrella' },
  { id: 'tent', emoji: '⛺', label: 'Tent' },
  { id: 'sleeping_bag', emoji: '🛌', label: 'Sleeping Bag' },

  // Plants & Gardening
  { id: 'rose', emoji: '🌹', label: 'Rose' },
  { id: 'tulip', emoji: '🌷', label: 'Tulip' },
  { id: 'sunflower', emoji: '🌻', label: 'Sunflower' },
  { id: 'cherry_blossom', emoji: '🌸', label: 'Cherry Blossom' },
  { id: 'white_flower', emoji: '💮', label: 'White Flower' },
  { id: 'lotus', emoji: '🪷', label: 'Lotus' },
  { id: 'hibiscus', emoji: '🌺', label: 'Hibiscus' },
  { id: 'cactus2', emoji: '🌵', label: 'Cactus' },
  { id: 'christmas_tree2', emoji: '🎄', label: 'Christmas Tree' },
  { id: 'evergreen_tree', emoji: '🌲', label: 'Evergreen Tree' },
  { id: 'deciduous_tree', emoji: '🌳', label: 'Deciduous Tree' },
  { id: 'palm_tree', emoji: '🌴', label: 'Palm Tree' },
  { id: 'seedling', emoji: '🌱', label: 'Seedling' },
  { id: 'herb', emoji: '🌿', label: 'Herb' },
  { id: 'shamrock', emoji: '☘️', label: 'Shamrock' },
  { id: 'four_leaf_clover', emoji: '🍀', label: 'Four Leaf Clover' },
  { id: 'bamboo', emoji: '🎋', label: 'Bamboo' },
  { id: 'rice', emoji: '🌾', label: 'Rice' },
  { id: 'wheat', emoji: '🌾', label: 'Wheat' },
  { id: 'corn2', emoji: '🌽', label: 'Corn' },
  { id: 'carrot2', emoji: '🥕', label: 'Carrot' },
  { id: 'potato', emoji: '🥔', label: 'Potato' },
  { id: 'tomato', emoji: '🍅', label: 'Tomato' },
  { id: 'eggplant', emoji: '🍆', label: 'Eggplant' },
  { id: 'cucumber', emoji: '🥒', label: 'Cucumber' },
  { id: 'lettuce', emoji: '🥬', label: 'Lettuce' },
  { id: 'broccoli2', emoji: '🥦', label: 'Broccoli' },
  { id: 'garlic', emoji: '🧄', label: 'Garlic' },
  { id: 'onion', emoji: '🧅', label: 'Onion' },
  { id: 'mushroom2', emoji: '🍄', label: 'Mushroom' },

  // Weather & Natural Phenomena
  { id: 'sunny', emoji: '☀️', label: 'Sunny' },
  { id: 'cloudy', emoji: '☁️', label: 'Cloudy' },
  { id: 'partly_cloudy', emoji: '⛅', label: 'Partly Cloudy' },
  { id: 'rainy', emoji: '🌧️', label: 'Rainy' },
  { id: 'stormy', emoji: '⛈️', label: 'Stormy' },
  { id: 'snowy', emoji: '🌨️', label: 'Snowy' },
  { id: 'foggy', emoji: '🌫️', label: 'Foggy' },
  { id: 'windy', emoji: '💨', label: 'Windy' },
  { id: 'rainbow2', emoji: '🌈', label: 'Rainbow' },
  { id: 'thunder', emoji: '⚡', label: 'Thunder' },
  { id: 'tornado', emoji: '🌪️', label: 'Tornado' },
  { id: 'hurricane', emoji: '🌀', label: 'Hurricane' },
  { id: 'comet', emoji: '☄️', label: 'Comet' },
  { id: 'fire', emoji: '🔥', label: 'Fire' },
  { id: 'droplet', emoji: '💧', label: 'Droplet' },
  { id: 'wave', emoji: '🌊', label: 'Wave' },
  { id: 'volcano2', emoji: '🌋', label: 'Volcano' },
  { id: 'earth_africa', emoji: '🌍', label: 'Earth' },
  { id: 'earth_americas', emoji: '🌎', label: 'Earth Americas' },
  { id: 'earth_asia', emoji: '🌏', label: 'Earth Asia' },
  { id: 'globe', emoji: '🌐', label: 'Globe' },
  { id: 'milky_way', emoji: '🌌', label: 'Milky Way' },

  // Celestial Objects
  { id: 'sun2', emoji: '☀️', label: 'Sun' },
  { id: 'moon2', emoji: '🌙', label: 'Moon' },
  { id: 'new_moon', emoji: '🌑', label: 'New Moon' },
  { id: 'waxing_crescent', emoji: '🌒', label: 'Waxing Crescent' },
  { id: 'first_quarter', emoji: '🌓', label: 'First Quarter' },
  { id: 'waxing_gibbous', emoji: '🌔', label: 'Waxing Gibbous' },
  { id: 'full_moon', emoji: '🌕', label: 'Full Moon' },
  { id: 'waning_gibbous', emoji: '🌖', label: 'Waning Gibbous' },
  { id: 'last_quarter', emoji: '🌗', label: 'Last Quarter' },
  { id: 'waning_crescent', emoji: '🌘', label: 'Waning Crescent' },
  { id: 'crescent_moon', emoji: '🌙', label: 'Crescent Moon' },
  { id: 'star3', emoji: '⭐', label: 'Star' },
  { id: 'glowing_star', emoji: '🌟', label: 'Glowing Star' },
  { id: 'shooting_star', emoji: '🌠', label: 'Shooting Star' },
  { id: 'sparkler2', emoji: '🎇', label: 'Sparkler' },
  { id: 'fireworks2', emoji: '🎆', label: 'Fireworks' },
  { id: 'rainbow3', emoji: '🌈', label: 'Rainbow' },
  { id: 'comet2', emoji: '☄️', label: 'Comet' },

  // Weapons (Fantasy)
  { id: 'sword', emoji: '⚔️', label: 'Sword' },
  { id: 'dagger2', emoji: '🗡️', label: 'Dagger' },
  { id: 'axe2', emoji: '🪓', label: 'Axe' },
  { id: 'hammer3', emoji: '🔨', label: 'Hammer' },
  { id: 'pick2', emoji: '⛏️', label: 'Pick' },
  { id: 'bow', emoji: '🏹', label: 'Bow' },
  { id: 'shield2', emoji: '🛡️', label: 'Shield' },
  { id: 'crossed_swords2', emoji: '⚔️', label: 'Crossed Swords' },
  { id: 'gun2', emoji: '🔫', label: 'Gun' },
  { id: 'bomb', emoji: '💣', label: 'Bomb' },
  { id: 'knife', emoji: '🔪', label: 'Knife' },
  { id: 'spear', emoji: '🔱', label: 'Spear' },

  // Containers & Storage
  { id: 'box', emoji: '📦', label: 'Box' },
  { id: 'package', emoji: '📦', label: 'Package' },
  { id: 'envelope', emoji: '✉️', label: 'Envelope' },
  { id: 'mailbox', emoji: '📫', label: 'Mailbox' },
  { id: 'mailbox_with_mail', emoji: '📬', label: 'Mailbox with Mail' },
  { id: 'mailbox_with_no_mail', emoji: '📭', label: 'Mailbox Empty' },
  { id: 'postbox', emoji: '📮', label: 'Postbox' },
  { id: 'basket', emoji: '🧺', label: 'Basket' },
  { id: 'shopping_bags', emoji: '🛍️', label: 'Shopping Bags' },
  { id: 'bag', emoji: '👜', label: 'Bag' },
  { id: 'pouch', emoji: '👛', label: 'Pouch' },
  { id: 'wallet', emoji: '👛', label: 'Wallet' },
  { id: 'coin', emoji: '🪙', label: 'Coin' },
  { id: 'gem', emoji: '💎', label: 'Gem' },
  { id: 'ring2', emoji: '💍', label: 'Ring' },
  { id: 'necklace', emoji: '📿', label: 'Necklace' },
  { id: 'lipstick', emoji: '💄', label: 'Lipstick' },
  { id: 'nail_polish', emoji: '💅', label: 'Nail Polish' },
  { id: 'lotion_bottle', emoji: '🧴', label: 'Lotion' },
  { id: 'safety_pin', emoji: '🧷', label: 'Safety Pin' },

  // Electronics & Gadgets
  { id: 'mobile_phone', emoji: '📱', label: 'Mobile Phone' },
  { id: 'iphone', emoji: '📱', label: 'iPhone' },
  { id: 'calling', emoji: '📞', label: 'Calling' },
  { id: 'telephone_receiver', emoji: '📞', label: 'Phone' },
  { id: 'pager', emoji: '📟', label: 'Pager' },
  { id: 'fax_machine', emoji: '📠', label: 'Fax' },
  { id: 'battery', emoji: '🔋', label: 'Battery' },
  { id: 'electric_plug', emoji: '🔌', label: 'Electric Plug' },
  { id: 'light_bulb', emoji: '💡', label: 'Light Bulb' },
  { id: 'flashlight', emoji: '🔦', label: 'Flashlight' },
  { id: 'candle2', emoji: '🕯️', label: 'Candle' },
  { id: 'diya_lamp', emoji: '🪔', label: 'Diya Lamp' },
  { id: 'magic_wand', emoji: '🪄', label: 'Magic Wand' },
  { id: 'joystick', emoji: '🕹️', label: 'Joystick' },
  { id: 'slot_machine', emoji: '🎰', label: 'Slot Machine' },
  { id: 'game_die', emoji: '🎲', label: 'Game Die' },
  { id: 'puzzle_piece', emoji: '🧩', label: 'Puzzle Piece' },
  { id: 'teddy_bear2', emoji: '🧸', label: 'Teddy Bear' },
  { id: 'spool_of_thread', emoji: '🧵', label: 'Spool of Thread' },
  { id: 'ball_of_yarn', emoji: '🧶', label: 'Ball of Yarn' },
  { id: 'safety_pin2', emoji: '🧷', label: 'Safety Pin' },
  { id: 'broom', emoji: '🧹', label: 'Broom' },
  { id: 'basket2', emoji: '🧺', label: 'Basket' },
  { id: 'roll_of_paper', emoji: '🧻', label: 'Roll of Paper' },
  { id: 'soap', emoji: '🧼', label: 'Soap' },
  { id: 'sponge', emoji: '🧽', label: 'Sponge' },
  { id: 'receipt', emoji: '🧾', label: 'Receipt' },
] as const;

export const getAvatarEmoji = (avatarId: string): string => {
  const avatar = avatars.find(a => a.id === avatarId);
  return avatar ? avatar.emoji : '👤';
};
